name: Build & Release

permissions:
    contents: write

on:
    workflow_dispatch:
        inputs:
            tag_name:
                description: "The tag name for the release (e.g., v1.0.0)"
                required: true
                type: string
            prerelease:
                description: "Set to true for a pre-release"
                required: false
                type: boolean
                default: false
            draft:
                description: "Set to true to create a draft release"
                required: false
                type: boolean
                default: false
    push:
        tags:
            - "v*"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build_and_release_apks:
        name: Build & Release APKs
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version-file: pubspec.yaml
                  cache: true
            
            - name: Get Dependencies
              run: flutter pub get

            - name: Build Split APKs
              run: flutter build apk --release --split-per-abi

            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  # Prioritize workflow_dispatch input, fallback to git ref for tag push
                  tag: ${{ github.event.inputs.tag_name || github.ref }}
                  prerelease: ${{ github.event.inputs.prerelease || false }}
                  draft: ${{ github.event.inputs.draft || false }}
                  artifacts: "build/app/outputs/apk/release/*.apk"
                  token: ${{ secrets.GITHUB_TOKEN }}

    build_web_artifact:
        name: Build Web Artifact
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version-file: pubspec.yaml
                  cache: true

            - name: Get Dependencies
              run: flutter pub get

            - name: Configure GitHub Pages
              id: pages
              uses: actions/configure-pages@v4

            - name: Build Web App
              run: flutter build web --release --pwa-strategy=offline-first --base-href "${{ steps.pages.outputs.base_path }}/"

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./build/web"

    deploy_pages:
        needs: build_web_artifact
        name: Deploy to GitHub Pages
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
