name: Build & Release

permissions:
    contents: write

on:
    workflow_dispatch:
        inputs:
            tag_name:
                description: "The tag name for the release (e.g., v1.0.0)"
                required: true
                type: string
            prerelease:
                description: "Set to true for a pre-release"
                required: false
                type: boolean
                default: false
            draft:
                description: "Set to true to create a draft release"
                required: false
                type: boolean
                default: false
    push:
        tags:
            - "v*"

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    get-version-info:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version.outputs.version }}
            build_number: ${{ steps.version.outputs.build_number }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get version from tag
              id: version
              run: |
                  version=${GITHUB_REF#refs/tags/}
                  echo "version=$version" >> $GITHUB_OUTPUT
                  echo "Release version: $version"
                  BUILD_NUMBER=$(grep '^version:' pubspec.yaml | sed 's/.*+//')
                  BUILD_NUMBER=$((BUILD_NUMBER * 10 + 3))
                  echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
    build:
        name: Build Release APKs
        needs: [get-version-info]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version-file: pubspec.yaml
                  cache: true

            - name: Flutter Doctor
              id: flutter_doctor
              run: |
                  flutter doctor -v

            - name: Get Dependencies
              run: flutter pub get

            # --- BUILD APKs ---
            - name: Build Split APKs
              run: flutter build apk --release --split-per-abi

            # --- PUBLISH ---
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  tag: ${{ github.event.inputs.tag_name }}
                  prerelease: ${{ github.event.inputs.prerelease }}
                  draft: ${{ github.event.inputs.draft }}
                  artifacts: "build/app/outputs/apk/release/*.apk"
                  token: ${{ secrets.GITHUB_TOKEN }}

    build_web_artifact:
        name: Build Web Artifact
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version-file: pubspec.yaml
                  cache: true

            - name: Get Dependencies
              run: flutter pub get

            - name: Configure GitHub Pages
              id: pages
              uses: actions/configure-pages@v4

            - name: Build Web App
              run: flutter build web --pwa-strategy=offline-first --base-href "${{ steps.pages.outputs.base_path }}/"

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./build/web"

    deploy_pages:
        needs: build_web_artifact
        name: Deploy to GitHub Pages
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
